# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MWQ5MTVmOThlYzE4ZjgzN2YyYzkxMWUxYWIxYTI0Mzk4MTZjM2Q3YTcwMzNjNTViZjZhNDYxMzliODI0OTJkZWM1Yjk5MDhmY2YxZmI3YjE1YmI4NTNhNTgwMDdiMjhkNTU4N2FjMTVmMDMwM2M2MDMzNTRiY2RhZmY1ZjhkNDc=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
