# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NmZhNjA4NGFkZDhmNjc3ODc1MWRkMzA2MmE1NTgwZjE5ZjM3MjU0YjE3MTA5OTllZTViNTBiMDdjMTZiYWE3MDkzMWQwMDRkYjQ3ZTcyZjgxZjgzYmU0NjBhMmU1YTRiOWVjM2ZlZGZkNzhjMzQ0N2FiYTkwNTk2ZWFkYjFhYTk=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
